sudo: required
language: javascript
services:
- docker
env:
- PROJECT_ID="stonestick-instant-messaging"
install:
- gcloud auth activate-service-account --key-file client-secret.json
- gcloud config set project "$PROJECT_ID"
script:
- docker build -t eu.gcr.io/$PROJECT_ID/users:$TRAVIS_COMMIT .
- gcloud docker push eu.gcr.io/$PROJECT_ID/users:$TRAVIS_COMMIT
before_install:
- openssl aes-256-cbc -K $encrypted_e71a02fb9f1f_key -iv $encrypted_e71a02fb9f1f_iv
  -in client-secret.json.enc -out client-secret.json -d
