sudo: required
language: javascript
services:
- docker
env:
  global:
    secure: TBlvocR9cdlepTzmTy/dtUL8NAwDOWHetya9zKQuYkPE2liflBIcS5+BwAgGvuYo7gzQ8lmgbTv1SUKoSFbp1ZhQ6GE8CwXQaBwHYsXFoOn7z/oeto24GHmg5haUgVDViBoa5Z+3V3OSlc3AGdWmFDtpGqZcdKz+xV9pJT1cIAJX029asKbq+h3NOZ8AzKKmrD9AHDNdSzXbVl3bSxEdrmbCHkoaii/tdXqS96+OrONKj+wjlR6HqF+zbUEXEVF72MlteReV//bTIdqEHwtdue0UrQmuytKj/sx/WLUdbzvzxswoll1Mzy1zF9WhNC+qBpdkNNC3Bb1h/AXFE0w8FQg4Or12VFBz5/MEcmp7AELhJ7wNDi36Vm2r7MU2Vyn6MrPdMcHjUmbgpKYP6LscUHBF8axafXncMPKEYbp5KCy9F6EJsOC89MY48fO79OL9wstWL3sYwiZPa2c1wKjxbbt9bCHMpkEDO+xlOMzA5UECs34BQ9iA6ltpt/uHtKA+lnGlJwwODhq3UyirZXM1Q2OOT432GG87K/E+oF+66ZaYgOF8x2yQHLvn4H+dfGW9nbQvc7PIpNdOuPF3tgrC1fI/uDLuiBiNxP2QjGL2H7AN6zlD0wwPCLCe7sCoM4wItGRHY51uiq2HC1CPUH4wY2OD+LWkaZfPgay9dJeiOlE=
install:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
- docker build -t $DOCKER_USERNAME/users:${TRAVIS_COMMIT::8} .
- docker push $DOCKER_USERNAME/users:${TRAVIS_COMMIT::8}