apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: users
  name: users
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: users
    spec:
      containers:
      - image: eu.gcr.io/stonestick-instant-messaging/users
        name: users
        ports:
        - name: users
          containerPort: 3290
          hostPort: 3290